// actionTypes.js
export const TOGGLE_GENRE_FILTER = 'TOGGLE_GENRE_FILTER';

// actionTypes.js
export const TOGGLE_RATING_FILTER = 'TOGGLE_RATING_FILTER';

// actionTypes.js
export const SET_RELEASE_YEARS = 'SET_RELEASE_YEARS';

export const SET_SEARCH_URL = 'SET_SEARCH_URL';

export const SET_AUDIENCE_SCORE = 'SET_AUDIENCE_SCORE';
// In your actionTypes.js file
export const APPEND_TO_RESULTS = 'APPEND_TO_RESULTS';

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_MAX_PAGE = 'SET_MAX_PAGE';
// For multi search slice
export const FETCH_MULTI_SEARCH_RESULTS_REQUEST = 'FETCH_MULTI_SEARCH_RESULTS_REQUEST'
export const FETCH_MULTI_SEARCH_RESULTS_SUCCESS = 'FETCH_MULTI_SEARCH_RESULTS_SUCCESS'
export const FETCH_MULTI_SEARCH_RESULTS_FAILURE = ' FETCH_MULTI_SEARCH_RESULTS_FAILURE'
export const CLEAR_MULTI_SEARCH_RESULTS = 'CLEAR_MULTI_SEARCH_RESULTS'
export const SET_MULTI_SEARCH_RESULTS = 'SET_MULTI_SEARCH_RESULTS';
export const SET_MULTI_SEARCH_MOVIE_PAGE = "SET_MULTI_SEARCH_MOVIE_PAGE";
export const SET_MULTI_SEARCH_TV_PAGE = "SET_MULTI_SEARCH_TV_PAGE"
export const SET_MULTI_SEARCH_PEOPLE_PAGE = "SET_MULTI_SEARCH_PEOPLE_PAGE"
export const APPEND_TO_MOVIE_MULTI_SEARCH_RESULTS = "APPEND_TO_MOVIE_MULTI_SEARCH_RESULTS"
export const APPEND_TO_TV_MULTI_SEARCH_RESULTS = "APPEND_TO_TV_MULTI_SEARCH_RESULTS"
export const APPEND_TO_PEOPLE_MULTI_SEARCH_RESULTS = "APPEND_TO_PEOPLE_MULTI_SEARCH_RESULTS"

